spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql:
      init:
        mode: always
        data-locations: classpath:/data.sql
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-topic
