name: Java CI with Gradle

# 어떤 조건에서 workflow를 실행할것인가.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  
jobs:
  build:
    # runs-on은 github action의 CI서버 runner가 어떤 환경을 갖출지
    runs-on: ubuntu-latest

    # name(옵션)이름을 적어주고 uses나 run으로 어떤일을 할지 적는다.
    # uses는 이미 만들어져있는 것을 가져다쓰는 것, run은 직접 명령어를 적어주겠다 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name : Make application.properties
      run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties

    - name: Build with Gradle
      run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    # - name: Build with Gradle Wrapper
    #   run: ./gradlew build
    
    - name: Docker build & push to docker repo
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest .
          docker push ${{ secrets.DOCKER_REPO }}

